name: Titanfall
version: 1.0.0
description: Titanfall in Minecraft!
author: KingFaris10
main: com.faris.titanfall.Main
depend: [CrackShot, Vault]
softdepend: [TagAPI]
commands:
    titanfall:
      description: Titanfall command.
      usage: /<command> [<args>]
      aliases: [tf, titanfalls, tfs]
    teamchat:
      description: Talk to other players on your team!
      usage: /<command> <message>
      aliases: [tc]
